name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # For consistent git commands in CI test runs!

      - uses: volta-cli/action@v4
        with:
          node-version: '24.7.0'
          yarn-version: '1.22.22'

      # Per https://stackoverflow.com/a/74732671, hopefully addresses current
      # failure of `yarn install --frozen-lockfile`
      - uses: actions/setup-python@v5.6.0
        with:
          python-version: '3.10'

      - run: yarn install --frozen-lockfile
      - run: yarn test
      - run: TZ=America/Los_Angeles yarn build

      - name: Dist tarball
        if: ${{ github.ref != 'refs/heads/main' }}
        run: tar -cvf dist.tar ./dist

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        if: ${{ github.ref != 'refs/heads/main' }}
        with:
          name: dist
          path: dist.tar

      - uses: JamesIves/github-pages-deploy-action@v4.7.3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          branch: gh-pages
          folder: dist
