name: build

on:
  push:
    branches:
      - features/gh-build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
          check-latest: true
      - run: yarn install
      - run: yarn build
