name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 14.21.3

      - run: yarn install --frozen-lockfile
      - run: yarn typecheck
      - run: yarn test
      - run: TZ=America/Los_Angeles yarn build

      - uses: JamesIves/github-pages-deploy-action@v4.7.3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          branch: gh-pages
          folder: dist
