# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json

name: build

on: push

defaults:
  run:
    shell: devenv shell bash -- -e {0}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0 # For consistent git commands in CI test runs!

      - uses: cachix/install-nix-action@1ca7d21a94afc7c957383a2d217460d980de4934 # v31.10.1
      - uses: cachix/cachix-action@3ba601ff5bbb07c7220846facfa2cd81eeee15a1 # v16
        with:
          name: devenv

      - name: Install devenv.sh
        shell: bash
        run: nix profile add nixpkgs#devenv

      - run: yarn install --frozen-lockfile
      - run: yarn test
      - run: TZ=America/Los_Angeles yarn build

      - name: Dist tarball
        if: ${{ github.ref != 'refs/heads/main' }}
        run: tar -cvf dist.tar ./dist

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        if: ${{ github.ref != 'refs/heads/main' }}
        with:
          name: dist
          path: dist.tar

      - uses: JamesIves/github-pages-deploy-action@v4.7.3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          branch: gh-pages
          folder: dist
